### ISSUE TITLE
Docker image is pw-protected?

### ISSUE THREAD

**Issue by michaelosthege** [sciapp/sampledb#1]
I just tried to run the container with the command from the readme:

```
docker run \
    -d \
    --link sampledb-postgres \
    -e SAMPLEDB_MAIL_SERVER=mail.example.com \
    -e SAMPLEDB_MAIL_SENDER=sampledb@example.com \
    -e SAMPLEDB_CONTACT_EMAIL=sampledb@example.com \
    -e SAMPLEDB_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:@sampledb-postgres:5432/postgres \
    -e SAMPLEDB_FILE_STORAGE_PATH=/home/sampledb/files/ \
    -v `pwd`/files:/home/sampledb/files:rw \
    --restart=always \
    --name sampledb \
    -p 8000:8000 \
    docker.pkg.github.com/sciapp/sampledb/sampledb:0.8.1
```

But I get this error:

```
Unable to find image 'docker.pkg.github.com/sciapp/sampledb/sampledb:0.8.1' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://docker.pkg.github.com/v2/sciapp/sampledb/sampledb/manifests/0.8.1: no basic auth credentials.
```

Is there anything I'm doing wrong?

cheers

**Comment by FlorianRhiem** [comment]
Hey, thank you for reporting this. I'm new to using GitHub packages, so I might have configured it wrong. It might be that GitHub expects people to sign in even for pulling images for public projects, but I'll look into it.

As a quick fix, you should be able to use this image without any authentication: `iffregistry.fz-juelich.de/docker-images/sampledb:0.8.1`

**Comment by FlorianRhiem** [comment]
Okay, this snippet form the [documentation](https://help.github.com/en/github/managing-packages-with-github-packages/about-github-packages#about-tokens) seems to indicate that you'd have to sign in to GitHub packages first:

> To install, publish, or delete a package, you must use a token with the appropriate scope, and your user account must have appropriate permissions for that repository.

I think I'll switch to another host for the Docker images then, as the images are meant to be fully public.

**Comment by FlorianRhiem** [comment]
I've pushed the image to Docker Hub as `sciapp/sampledb:0.8.1` and updated the repo accordingly.

**Comment by michaelosthege** [comment]
I can pull it now, awesome, thank you!
