### ISSUE TITLE
Files cannot be downloaded using the HTTP API

### ISSUE THREAD

**Issue by nilsholle** [sciapp/sampledb#11]
The [documentation](https://scientific-it-systems.iffgit.fz-juelich.de/SampleDB/developer_guide/api.html) does not show how to download files via the HTTP API; is this possible (yet)?

**Comment by FlorianRhiem** [comment]
Hey @nilsholle,

there are several types of files, e.g. ones which just store a url, and those who locally store the whole file. The documentation shows how to [read the content of a file](https://scientific-it-systems.iffgit.fz-juelich.de/SampleDB/developer_guide/api.html#reading-information-for-a-file) with a URL file as an example, but this works equally for files with local storage. In that case, when sending a `GET` request to the API URL of that file, you will get a property `base64_content` in the JSON object that contains the base64 encoded content of the file, along with the original file name. This pretty much identical to what you provide when you upload the file via the API.

I hope this helps!

**Comment by nilsholle** [comment]
Ah I should have read the "Response JSON Object" part more carefully. Thank you!
