### ISSUE TITLE
Action ID not shown in web frontend

### ISSUE THREAD

**Issue by nilsholle** [sciapp/sampledb#12]
I couldn't find any way to display the action IDs in the web frontend. I think they should be visible in several places:

- On the main page of an action
- In the action overview
- In the overview page of a specific object (sample or measurement)

**Comment by FlorianRhiem** [comment]
Hey @nilsholle 

true, currently you'd have to check the URL to get the Action ID. It should be displayed similarly to objects, groups, etc. like you said. Same should be done for locations. I'll fix it next week. Thanks!

**Comment by FlorianRhiem** [comment]
This was fixed in 10e57b5bcead28836db9e0894fc96fbc922e23d1, which has now been merged into the development version.
