### ISSUE TITLE
Make branding editable

### ISSUE THREAD

**Issue by nilsholle** [sciapp/sampledb#14]
Right now, there is a branding like "SampleDB is the sample and measurement metadata database at PGI and JCNS." in multiple places in SampleDB. Maybe I'm just missing something, but I couldn't find any way to change that.
If this is currently not possible, could we maybe make it possible to change those texts (via the administrator settings or an environment variable)?

**Comment by FlorianRhiem** [comment]
Hey @nilsholle,
there are several configuration variables for this branding, you can find them in the [configuration documentation](
https://scientific-it-systems.iffgit.fz-juelich.de/SampleDB/administrator_guide/configuration.html#customization). If I remember correctly right now, the `SAMPLEDB_SERVICE_DESCRIPTION` is the environment variable you need to set for the text you quoted. If you come across branding that cannot be customized in this way, just let me know, as that's not my intention.

**Comment by nilsholle** [comment]
Sorry for the late reply; yes, that helped a lot and I could have seen that in the documentation. Thank you!
