### ISSUE TITLE
Missing space

### ISSUE THREAD

**Issue by nilsholle** [sciapp/sampledb#16]
Some space seems to be missing between "Cancel" and "Save" below the action editor:

![grafik](https://user-images.githubusercontent.com/9198471/117541133-bf480480-b012-11eb-859c-6deb89ee5428.png)

It's just a very minor thing, but I thought I would just mention it here.

**Comment by FlorianRhiem** [comment]
Hey @nilsholle,
thank you for reporting this. Sure, it's very minor, but this way it got fixed :) The buttons looked fine with a wider browser window, so I hadn't noticed the overlap before. It was fixed in 8ba5439322d25e1e2cbbad5084412a2c08ba274d.
