### ISSUE TITLE
Save template

### ISSUE THREAD

**Issue by chsaikeerthi** [sciapp/sampledb#38]
Hello,

When we create a search query, is there an option to store the search template(same conditions) and use that later, to use the search multiple number of times?

**Comment by FlorianRhiem** [comment]
Hey @chsaikeerthi,

there is nothing built-in for this, but you could simply create a bookmark for it, as the query will be re-evaluated each time. Does this solve your use case?

**Comment by chsaikeerthi** [comment]
Yes this is pretty clear now. Thank You
