### ISSUE TITLE
SampleDB API Python

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#41]
Hey,
for those of you who already use SampleDB and want to digitize their lab equipment: @nilsholle and I have written a small Python library. With this you can write small programs to upload data, evaluate data or make simple changes to the samples automatically.

For all who are interested, the documentation with examples is available [here](https://ag-salinga.zivgitlabpages.uni-muenster.de/sampledb-api-wrapper/index.html). The PyPI package can be found [here](https://pypi.org/project/sampledbapi/).

**Comment by FlorianRhiem** [comment]
Hey Nils, thank you for writing this API wrapper!

**Comment by maltedeckers** [comment]
Thank you, @NilsWeber98 and @nilsholle!
Additionally to the WWU Gitlab, do you plan to publish the sourcecode in a way that allows contributions to extend the wrappers, i.e. here on github?

**Comment by nilsholle** [comment]
Hi Malte, as the CI pipeline is set up to run on Gitlab, I would prefer leaving the main repo there. However, I think mirroring the code to Github might be a good idea (at least other projects do it that way). Maybe it makes sense to do that as part of your sciapp organization?

**Comment by FlorianRhiem** [comment]
We do just that for SampleDB and other projects, developing it on our GitLab instance and [mirroring it as part of the CI pipeline](https://github.com/sciapp/sampledb/blob/1f4a32511c97ddccf53eb6ad8e8615fd88a3f4d3/.gitlab-ci.yml#L153). As `sciapp` is the Scientific IT-Systems team of PGI/JCNS-TA, it'd probably be better if you mirror it to a repo for your group?

**Comment by nilsholle** [comment]
Ok, sounds good! We will do that some time in the next few days. As discussed via email, we will also convert the Python API to camel case, so there will be quite a lot of changes in the next version - it might make sense to wait for that before using the API.

**Comment by FlorianRhiem** [comment]
Great, in that case I'll wait before adding [this paragraph](https://florianrhiem.iffgit.fz-juelich.de/-/SampleDB/-/jobs/518984/artifacts/build_documentation/developer_guide/api.html) to the HTTP API docs, and merge it once 0.6 is out. If you adapt the code style to PEP8, I've been pretty happy with the [pycodestyle](https://pypi.org/project/pycodestyle/) tool as an automated checker in the CI pipeline.

**Comment by nilsholle** [comment]
I just released version 0.6.0. The code is now also available [here](https://github.com/AG-Salinga/sampledb-api-wrapper) and all methods are snake case instead of camel case.

**Comment by NilsWeber98** [comment]
Thank you for adding this to the HTTP API docs.
