### ISSUE TITLE
Required text fields not required (+Required * missing)

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#43]
Hej,

during creating and testing multiple actions, I was able to not fill required text fields. I created some required text fields. However, I was able to save and create a object without that information. Additionally, I was able to leave empty the name in the action.

See simple example action to reproduce:

```
{
    "title": "",
    "type": "object",
    "properties": {
        "name": {
            "title": "Name",
            "type": "text"
        },
        "text": {
            "title": "Text",
            "type": "text"
        }
    },
    "required": [
        "name",
        "text"
    ],
    "propertyOrder": [
        "name",
        "text"
    ]
}
```

See empty result:

![image](https://user-images.githubusercontent.com/23240641/205656101-11fa39af-2609-4b67-b2d6-acd1e596553b.png)

Additionally, the * indicating the required field like in this case is not visible as well.

![image](https://user-images.githubusercontent.com/23240641/205656728-0e4d357c-0da3-4c0a-bb13-8a9d1d85c50b.png)

Our version is based on commit 04dff4bc0feae2bb41f606ea8bf2241a45c79d99

**Comment by FlorianRhiem** [comment]
If you set a `minLength`, it will require input. Otherwise empty input will be the valid text `""`, an empty string. The * would be misleading in that case.

**Comment by NilsWeber98** [comment]
I see your point. Thank you!
If I add the pattern option (e.g. "pattern": "[A-Z][0-9]"), there is still no * appearing. I think the * star would be helpful there as well. But now I know how to get it by adding minLength as well.
