### ISSUE TITLE
Change/hide action after making it public

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#46]
I created some test actions. While playing around, I made some of them public and lost the power to change it back, change parts of the action, or even hide the action. If it is intentional to not change public actions, I think as an admin, I should be able to hide it.

We are using the version based on https://github.com/sciapp/sampledb/commit/04dff4bc0feae2bb41f606ea8bf2241a45c79d99

**Comment by FlorianRhiem** [comment]
Can you edit the action permissions? As administrator, have you enable administrator permissions in the preferences (almost all the way at the bottom).
