### ISSUE TITLE
Cannot save changes in schema of action

### ISSUE THREAD

**Issue by dnlsch** [sciapp/sampledb#47]
I created a new action by using the template of an existing action. In the Figure below I added a property "description":

![grafik](https://user-images.githubusercontent.com/118688572/205687713-c323fdb5-7792-4d64-adcf-3779404c1be5.png)

Schema JSON:

```
{
    "title": "Simulation",
    "type": "object",
    "properties": {
        "name": {
            "title": "Name",
            "note": "Test2",
            "type": "text"
        },
        "tags": {
            "type": "tags",
            "title": "Tags"
        },
        "description": {
            "title": "Description",
            "type": "text",
            "markdown": true
        }
    },
    "required": [
        "name",
        "tags"
    ],
    "propertyOrder": [
        "name",
        "description",
        "tags"
    ]
}
```

Enabling the Note-field to save a hint there, it seems only possible when I use "Text (Simple)" as Type. When using e.g. "Text (Markdown)" or "Datetime" the Note-field resets to NaN and disabled after clicking on "Save". I think that is not intended.

**Comment by maltedeckers** [comment]
Thank you for reporting this bug.
It was fixed in 9f434b72a96f486a842a84325a055a99c6786668
