### ISSUE TITLE
Enhancement: Generating label batch

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#50]
Since we are planning to use the very nice QR code label feature of sampledb, it would be really useful to have batch generation for this feature.

We are currently creating multiple samples in one step using the batch action function. (*Thanks for the great batch function*).
Right now, we have to generate the labels for each sample step by step (it generates a whole sheet of paper with the same label). It would be useful to have a single generation step for all samples or for the samples selected via a checkbox.

**Comment by FlorianRhiem** [comment]
One of my colleagues is currently working on a feature for selecting multiple objects from the object list (via checkboxes, as you describe) and performing common tasks on them, such as assigning a new location or responsible user. The feature you are describing sounds like something that would fit in quite well with what he's working on.

**Comment by FlorianRhiem** [comment]
This has been implemented in v0.22.0:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/4411847/232406134-ef9b2c80-d921-4970-ab87-5af15394f3c6.png">

<img width="501" alt="image" src="https://user-images.githubusercontent.com/4411847/232406185-533db324-1b42-4bf2-8aa4-30200e1abc6e.png">
