### ISSUE TITLE
Get related objects with HTTP-API

### ISSUE THREAD

**Issue by NilsWeber98** [sciapp/sampledb#51]
In our system, we connected objects of different action types. The connection can be seen in the area "related objects" of both objects, but we are not able to get those related objects from the HTTP-API. Is there a way to achieve this? If so, where is it described?

**Comment by FlorianRhiem** [comment]
Hey Nils,
there are two kinds of related objects:
- objects which are referenced in the metadata of the current object, which you could find by going through the metadata yourself, which would be needlessly tedious to implement yourself, and
- objects which reference the other object, for which there is no reasonable way of finding them via the API.
In the code, [`get_related_object_ids`](https://github.com/sciapp/sampledb/blob/b686abc5fc720a02546c14af49e1ef7a23318747/sampledb/logic/object_relationships.py#L14) finds lists for these two categories and [`build_related_objects_tree`](https://github.com/sciapp/sampledb/blob/b686abc5fc720a02546c14af49e1ef7a23318747/sampledb/logic/object_relationships.py#L65) constructs the tree structure shown in the related objects section using `get_related_object_ids` repeatedly. I suspect for your use case, the ID lists for a given object would be sufficient? If so, I think an API route should be added to return these.

**Comment by NilsWeber98** [comment]
Hey Florian,
thank you for the quick response. Unfortunately, we are looking for objects which are not referenced in the metadata of the current object. An additional API route covering this case would be helpful.

**Comment by FlorianRhiem** [comment]
I've implemented this in fedc033b5041dbd732b86a9a6a0eacbc96cd7148, these lists can now be accessed via [`/api/v1/objects/<object_id>/related_objects`](https://scientific-it-systems.iffgit.fz-juelich.de/SampleDB/developer_guide/api.html#getting-related-object-ids).
