### ISSUE TITLE
type: file is considered as invalid type

### ISSUE THREAD

**Issue by link89** [sciapp/sampledb#52]
Hi, I find that when I set `type: file` in the schema editor and click save, I would receive a error message `invalid type`.

I am using v0.22.1 docker image BTW.

Here is the schema 
```json
{
    "title": {
        "en": "Ramen Spectrum"
    },
    "type": "object",
    "properties": {
        "name": {
            "title": {
                "en": "Name"
            },
            "type": "text"
        },
        "spectrum": {
            "title": {
                "en": "Spectrum"
            },
            "type": "file"
        }
    },
    "required": [
        "name"
    ],
    "propertyOrder": [
        "name",
        "spectrum"
    ]
}
```

![image](https://github.com/sciapp/sampledb/assets/3314130/489f6002-161f-4ab7-9710-95a8f2812096)

**Comment by FlorianRhiem** [comment]
Hey @link89, the `file` property type is part of the current development version and will be part of release 0.23. You can try it out by using the image `sciapp/sampledb:develop`. Without the `file` property type, users can still upload files, they just can't assign them to metadata fields.
